INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'h', 'en-CA', 'Humour, satires, etc.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '132', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '119', 'en-CA', 'Allow a user to delete a non catalogued type');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '134', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '125', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '131', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '127', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '133', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '126', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('pgt.name', '4', 'en-CA', 'Cataloguers');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '72', 'en-CA', 'Allow a user to create a new non-catalogued item type');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '11', 'en-CA', 'Cataloguing');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '73', 'en-CA', 'Allow a user to update a non-catalogued item type');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '130', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '135', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '136', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '128', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'en-CA', 'Allow a user to add/remove users to/from the "Cataloguer" group');
