INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '11', 'es-ES', 'ID interno');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'vai', 'es-ES', 'Vai');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cblvl.value', 'i', 'es-ES', 'Integrando recurso');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'u', 'es-ES', 'Desconocido');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'p', 'es-ES', 'Poesía');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '6', 'es-ES', 'En transito');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'pau', 'es-ES', 'Palauan');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '194', 'es-ES', 'Permitir a un usuario crear órdenes de compra');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '5', 'es-ES', 'Título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '14', 'es-ES', 'Título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '23', 'es-ES', 'Título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kir', 'es-ES', 'Kyrgyz');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'en-US', 'es-ES', 'Inglés de EE.UU.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'niu', 'es-ES', 'Niuean');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'fat', 'es-ES', 'Fanti');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '3', 'es-ES', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '12', 'es-ES', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '21', 'es-ES', 'LCCN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mas', 'es-ES', 'Masai');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bam', 'es-ES', 'Bambara');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'snd', 'es-ES', 'Sindhi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aou.name', '7', 'es-ES', 'Rama de ejemplo 4');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'abk', 'es-ES', 'Abkhaz');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sat', 'es-ES', 'Santali');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'dua', 'es-ES', 'Duala');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ukr', 'es-ES', 'Ucraniano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'vot', 'es-ES', 'Votic');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cubt.label', 'folks:circ.view', 'es-ES', 'Ver circulaciones');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aou.name', '5', 'es-ES', 'Rama de ejemplo 2');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'h', 'es-ES', 'Humor, sátiras, etc.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '43', 'es-ES', 'Permitir a un usuario crear una nueva factura en esta transacción');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bnt', 'es-ES', 'Bantú (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kau', 'es-ES', 'Kanuri');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'umb', 'es-ES', 'Umbundu');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '41', 'es-ES', 'Permitir a un usuario crear una nueva transacción facturable');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cubt.label', 'folks:circ.renew', 'es-ES', 'Renovar circulaciones');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '188', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'cel', 'es-ES', 'Celta (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'hil', 'es-ES', 'Hiligaynon');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kac', 'es-ES', 'Kachin');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '164', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'j', 'es-ES', 'Historias cortas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'pag', 'es-ES', 'Pangasinan');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '156', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '182', 'es-ES', 'Permitir a los usuarios marcar el estado de un elemento como ''disponible''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '82', 'es-ES', 'Permitir a un usuario ver que usuarios han realizado retiros de una copia en particular');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'pam', 'es-ES', 'Pampanga');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nah', 'es-ES', 'Nahuatl');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'yid', 'es-ES', 'Yiddish');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '117', 'es-ES', 'Permitir a un usuario actualizar un intervalo de fecha cerrado para una ubicación dada');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ton', 'es-ES', 'Tongan');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ijo', 'es-ES', 'Ijo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'cai', 'es-ES', 'Indígenas Centro Americanos (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '14', 'es-ES', 'Dañado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '132', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sma', 'es-ES', 'Sami del sur');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kaw', 'es-ES', 'Kawi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kok', 'es-ES', 'Konkani');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nau', 'es-ES', 'Nauru');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cam.value', 'g', 'es-ES', 'General');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sas', 'es-ES', 'Sasak');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '0', 'es-ES', 'Disponible');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '180', 'es-ES', 'Permitir a un usuario marcar una transacción como morosa (irrecuperable)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'zul', 'es-ES', 'Zulú');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '87', 'es-ES', 'Permitir a un usuario ver las notas adjuntas a un título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'geo', 'es-ES', 'Georgiano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '155', 'es-ES', 'Permitir a un usuario ver la fuentes de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'arc', 'es-ES', 'Arameo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '84', 'es-ES', 'Permitir a un usuario registrar una nueva estación de trabajo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tir', 'es-ES', 'Tigrinya');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tib', 'es-ES', 'Tibetano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '7', 'es-ES', 'Editorial');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '16', 'es-ES', 'Editorial');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '25', 'es-ES', 'Editorial');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '12', 'es-ES', 'Editorial');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'inh', 'es-ES', 'Ingush');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'dzo', 'es-ES', 'Dzongkha');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'grn', 'es-ES', 'Guaraní');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', '-gua', 'es-ES', 'Guaraní');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'iii', 'es-ES', 'Yi Sinchuán');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'btk', 'es-ES', 'Batak');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'div', 'es-ES', 'Divehi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kru', 'es-ES', 'Kurukh');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'her', 'es-ES', 'Herero');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'eng', 'es-ES', 'Inglés');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'scr', 'es-ES', 'Croata');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cam.value', 'j', 'es-ES', 'Juvenil');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'chi', 'es-ES', 'Chino');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '51', 'es-ES', 'Permitir a un usuario agregar a otros usuarios a los grupos de permisos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'iku', 'es-ES', 'Inuktitut');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'pli', 'es-ES', 'Palí');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'gaa', 'es-ES', 'Gã');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '119', 'es-ES', 'Permitir a un usuario eliminar un tipo no catalogado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'yap', 'es-ES', 'Yapese');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ara', 'es-ES', 'Árábe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ven', 'es-ES', 'Venda');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('pgt.name', '3', 'es-ES', 'Personal');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '134', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value''in', 'gwi', 'es-ES', 'Gwich');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ori', 'es-ES', 'Oriya');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '125', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ipk', 'es-ES', 'Inupiaq');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'en-CA', 'es-ES', 'Inglés (Canadá)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'hin', 'es-ES', 'Hindú');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ewo', 'es-ES', 'Ewondo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'hun', 'es-ES', 'Húngaro');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'f', 'es-ES', 'Novelas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'wol', 'es-ES', 'Wolof');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bos', 'es-ES', 'Bosnio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'vie', 'es-ES', 'Vietnamita');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aout.opac_label', '4', 'es-ES', 'Esta biblioteca especializada');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mnc', 'es-ES', 'Manchú');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'rus', 'es-ES', 'Ruso');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'ru-RU', 'es-ES', 'Ruso');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'ru-RU', 'es-ES', 'Ruso');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'gba', 'es-ES', 'Gbaya');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'luo', 'es-ES', 'Luo (Kenia y Tanzania)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tiv', 'es-ES', 'Tiv');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'und', 'es-ES', 'Indeterminado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '90', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cnal.name', '3', 'es-ES', 'Sin acceso');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bra', 'es-ES', 'Braj');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bat', 'es-ES', 'Bálticas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tso', 'es-ES', 'Tsonga');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('citm.value', 'm', 'es-ES', 'Archivo de computadora');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'phi', 'es-ES', 'Filipino (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ger', 'es-ES', 'Alemán');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '131', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sla', 'es-ES', 'Eslavas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'baq', 'es-ES', 'Vasco');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tum', 'es-ES', 'Tumbuka');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cbs.source', '1', 'es-ES', 'oclc');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('pgt.name', '6', 'es-ES', 'Adquisiciones');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mdr', 'es-ES', 'Mandar');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'che', 'es-ES', 'Checheno');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nzi', 'es-ES', 'Nzima');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'dut', 'es-ES', 'Holandés');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'eka', 'es-ES', 'Ekajuk');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'grb', 'es-ES', 'Grebo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nep', 'es-ES', 'Nepalés');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '127', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sms', 'es-ES', 'Sami Skolt');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '4', 'es-ES', 'Faltante');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'wel', 'es-ES', 'Galés');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ota', 'es-ES', 'Turco, Otomano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '6', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '15', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '24', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '6', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'goh', 'es-ES', 'Alemán Arcaico (ca. 750-1050)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tem', 'es-ES', 'Temne');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cubt.label', 'folks', 'es-ES', 'Amigos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'day', 'es-ES', 'Dayak');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'gon', 'es-ES', 'Gondi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '28', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bak', 'es-ES', 'Bashkir');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '183', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kam', 'es-ES', 'Kamba');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'es-MX', 'es-ES', 'Español (México)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '76', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '161', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'i', 'es-ES', 'Letras');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bih', 'es-ES', 'Biharí');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ine', 'es-ES', 'Indoeuropeas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kin', 'es-ES', 'Kinyarwanda');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ile', 'es-ES', 'Interlingua');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccs.name', '12', 'es-ES', 'Reservas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'heb', 'es-ES', 'Hebreo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'lit', 'es-ES', 'Lituano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'epo', 'es-ES', 'Esperanto');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', '-esp', 'es-ES', 'Esperanto');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'inc', 'es-ES', 'Índicas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tel', 'es-ES', 'Telugú');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '4', 'es-ES', 'Autor');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '13', 'es-ES', 'Autor');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '22', 'es-ES', 'Autor');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cbs.source', '2', 'es-ES', 'Sistema local');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '154', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'new', 'es-ES', 'Newari');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cnal.name', '2', 'es-ES', 'Sin filtrar');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '133', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '25', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ful', 'es-ES', 'Fula');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cifm.value', 'a', 'es-ES', 'Microfilm');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nub', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'arm', 'es-ES', 'Armenio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.name', 'hy-AM', 'es-ES', 'Armenio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'hy-AM', 'es-ES', 'Armenio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '126', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bad', 'es-ES', 'Banda');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tam', 'es-ES', 'Tamil');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'aus', 'es-ES', 'Idiomas australianos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cam.value', '', 'es-ES', 'Desconocido o no especificado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'din', 'es-ES', 'Dinka');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'chu', 'es-ES', 'Eslávico eclesiástico');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nno', 'es-ES', 'Noruego (Nynorsk)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'lam', 'es-ES', 'Lamba');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', '-gag', 'es-ES', 'Gallego');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'glg', 'es-ES', 'Gallego');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mad', 'es-ES', 'Madurese');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kmb', 'es-ES', 'Kimbundu');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ssa', 'es-ES', 'Nilo-Saharianas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kha', 'es-ES', 'Khasi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'man', 'es-ES', 'Mandingo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mah', 'es-ES', 'Marshalés');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'yao', 'es-ES', 'Yao (África)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mar', 'es-ES', 'Maratí');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'slv', 'es-ES', 'Esloveno');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'san', 'es-ES', 'Sánscrito');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clfm.value', 'e', 'es-ES', 'Ensayos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'elx', 'es-ES', 'Elamita');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '161', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '53', 'es-ES', 'Permitir a un usuario agregar a otros usuarios a los grupos de permisos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccpbt.label', 'misc', 'es-ES', 'Varios');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ccnbt.label', 'misc', 'es-ES', 'Varios');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cbrebt.label', 'misc', 'es-ES', 'Varios');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cubt.label', 'misc', 'es-ES', 'Varios');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nor', 'es-ES', 'Noruego');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'lug', 'es-ES', 'Ganda');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aout.opac_label', '1', 'es-ES', 'En todos lados');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aou.name', '6', 'es-ES', 'Rama de ejemplo 4');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('aou.name', '4', 'es-ES', 'Rama de ejemplo 4');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'lah', 'es-ES', 'Lahnda');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'hit', 'es-ES', 'Hitita');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tuk', 'es-ES', 'Turkmenio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'suk', 'es-ES', 'Sukuma');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '72', 'es-ES', 'Permitir a un usuario eliminar un tipo no catalogado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '73', 'es-ES', 'Permitir a un usuario eliminar un tipo no catalogado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ypk', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bej', 'es-ES', 'Beja');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'gem', 'es-ES', 'Germánicas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '9', 'es-ES', 'Tipo de elemento');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '18', 'es-ES', 'Tipo de elemento');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '27', 'es-ES', 'Tipo de elemento');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kab', 'es-ES', 'Kabyle');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cit.name', '2', 'es-ES', 'Número de Seguro Social');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'got', 'es-ES', 'Gótico');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tmh', 'es-ES', 'Tamashek');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'kaa', 'es-ES', 'Kara-Kalpak');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'swa', 'es-ES', 'Suahili');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'car', 'es-ES', 'Caribe');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sam', 'es-ES', 'Arameo Samaritano');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'chr', 'es-ES', 'Cherokee');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mag', 'es-ES', 'Magahi');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'paa', 'es-ES', 'Papuas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', '-mla', 'es-ES', 'Malgache');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mlg', 'es-ES', 'Malgache');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tli', 'es-ES', 'Tlingit');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mao', 'es-ES', 'Maorí');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'frm', 'es-ES', 'Francés medieval (ca. 1400-1600)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bai', 'es-ES', 'Bamileke, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ibo', 'es-ES', 'Igbo');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'lad', 'es-ES', 'Ladino (Judeo-español)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'cat', 'es-ES', 'Catalán');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'srr', 'es-ES', 'Serer');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cam.value', 'e', 'es-ES', 'Adulto');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'phn', 'es-ES', 'Fenicio');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'wen', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '77', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '2', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '11', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('cza.label', '20', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('vqbrad.description', '5', 'es-ES', 'ISSN');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '190', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '88', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '76', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '161', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '192', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '200', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '199', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'myn', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'ace', 'es-ES', 'Chino');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '38', 'es-ES', 'Permitir a los usuarios marcar el estado de un elemento como ''disponible''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '186', 'es-ES', 'Permitir a los usuarios marcar el estado de un elemento como ''disponible''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '185', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '162', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '167', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '39', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '37', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '185', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '186', 'es-ES', 'Permitir a los usuarios marcar el estado de un elemento como ''disponible''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'bul', 'es-ES', 'Húngaro');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '32', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mno', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'myn', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '24', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '76', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '161', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '89', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'oto', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '158', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '201', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '199', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '160', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tut', 'es-ES', 'Celta (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '73', 'es-ES', 'Permitir a un usuario eliminar un tipo no catalogado');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '168', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '167', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '184', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mga', 'es-ES', 'Francés medieval (ca. 1400-1600)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'dum', 'es-ES', 'Francés medieval (ca. 1400-1600)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'mga', 'es-ES', 'Francés medieval (ca. 1400-1600)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sai', 'es-ES', 'Indígenas Centro Americanos (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'es-MX', 'es-ES', 'Inglés de EE.UU.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'es-US', 'es-ES', 'Inglés de EE.UU.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '130', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'jpr', 'es-ES', 'Judeo-Persa');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '97', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '76', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '161', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '37', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '185', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '174', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '21', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sem', 'es-ES', 'Celta (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '85', 'es-ES', 'Permitir a un usuario ver las notas adjuntas a un título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '169', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '167', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '86', 'es-ES', 'Permitir a un usuario ver las notas adjuntas a un título');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '75', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '187', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '23', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '195', 'es-ES', 'Permitir a un usuario crear órdenes de compra');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '135', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '14', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '28', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sgn', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '136', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'chm', 'es-ES', 'Maorí');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'tup', 'es-ES', 'Nubias, lenguas');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('i18n_l.description', 'es-US', 'es-ES', 'Inglés de EE.UU.');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '128', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'cus', 'es-ES', 'Celta (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '159', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '158', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'nai', 'es-ES', 'Indígenas Centro Americanos (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '52', 'es-ES', 'Permitir a un usuario agregar a otros usuarios a los grupos de permisos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '191', 'es-ES', 'Permitir a un usuario marcar el estado de un elemento como ''en transito''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'guj', 'es-ES', 'Guaraní');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '19', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '199', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '116', 'es-ES', 'Permitir a un usuario actualizar un intervalo de fecha cerrado para una ubicación dada');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '26', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '78', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sme', 'es-ES', 'Sami del sur');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '129', 'es-ES', 'Permitir a un usuario agregar/eliminar usuarios de/desde el grupo "LibraryManager"');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '21', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('clm.value', 'sio', 'es-ES', 'Papuas (Otras)');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '199', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '166', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '157', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '153', 'es-ES', 'Permitir a un usuario actualizar la fuente de fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '189', 'es-ES', 'Permitir a los usuarios marcar el estado de un elemento como ''disponible''');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '163', 'es-ES', 'Permitir a un usuario actualizar el destino de los fondos');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '306', 'es-ES', 'FIXME: Falta descripción para UPDATE_LOCALE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '342', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.cat.bib.alert_on_empty');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '223', 'es-ES', 'FIXME: Falta descripción para CREATE_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '237', 'es-ES', 'FIXME: Falta descripción para DELETE_LASSO');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '262', 'es-ES', 'FIXME: Falta descripción para UPDATE_ITEM_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '332', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.hold_boundary.soft');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '257', 'es-ES', 'FIXME: Falta descripción para UPDATE_CIRC_MOD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '245', 'es-ES', 'FIXME: Falta descripción para DELETE_ORG_UNIT_CLOSING');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '226', 'es-ES', 'FIXME: Falta descripción para UPDATE_VR_FORMAT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '255', 'es-ES', 'FIXME: Falta descripción para UPDATE_BIB_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '225', 'es-ES', 'FIXME: Falta descripción para CREATE_SURVEY');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '274', 'es-ES', 'FIXME: Falta descripción para UPDATE_RELEVANCE_ADJUSTMENT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '233', 'es-ES', 'FIXME: Falta descripción para DELETE_HOURS_OF_OPERATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '253', 'es-ES', 'FIXME: Falta descripción para TRANSIT_COPY');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '292', 'es-ES', 'FIXME: Falta descripción para DELETE_AUTHORITY_IMPORT_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '242', 'es-ES', 'FIXME: Falta descripción para DELETE_ORG_ADDRESS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '213', 'es-ES', 'FIXME: Falta descripción para CREATE_LANGUAGE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '207', 'es-ES', 'FIXME: Falta descripción para CREATE_CIRC_DURATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '266', 'es-ES', 'FIXME: Falta descripción para UPDATE_LASSO_MAP');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '329', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.void_overdue_on_lost');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '289', 'es-ES', 'FIXME: Falta descripción para CREATE_MARC_CODE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '210', 'es-ES', 'FIXME: Falta descripción para CREATE_HOURS_OF_OPERATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '214', 'es-ES', 'FIXME: Falta descripción para CREATE_LASSO');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '311', 'es-ES', 'FIXME: Falta descripción para CREATE_IMPORT_ITEM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '227', 'es-ES', 'FIXME: Falta descripción para CREATE_XML_TRANSFORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '279', 'es-ES', 'FIXME: Falta descripción para UPDATE_XML_TRANSFORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '301', 'es-ES', 'FIXME: Falta descripción para UPDATE_AUTHORITY_IMPORT_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '294', 'es-ES', 'FIXME: Falta descripción para DELETE_AUTHORITY_RECORD_NOTE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '265', 'es-ES', 'FIXME: Falta descripción para UPDATE_LASSO');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '212', 'es-ES', 'FIXME: Falta descripción para CREATE_ITEM_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '256', 'es-ES', 'FIXME: Falta descripción para UPDATE_CIRC_DURATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '324', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.auth.staff_timeout');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '277', 'es-ES', 'FIXME: Falta descripción para UPDATE_VOLUME_NOTE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '293', 'es-ES', 'FIXME: Falta descripción para DELETE_AUTHORITY_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '320', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING_ALL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '271', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '275', 'es-ES', 'FIXME: Falta descripción para UPDATE_SURVEY');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '222', 'es-ES', 'FIXME: Falta descripción para CREATE_ORG_UNIT_CLOSING');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '251', 'es-ES', 'FIXME: Falta descripción para DELETE_XML_TRANSFORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '315', 'es-ES', 'FIXME: Falta descripción para DELETE_IMPORT_ITEM_ATTR_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '308', 'es-ES', 'FIXME: Falta descripción para UPDATE_TRANSLATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '261', 'es-ES', 'FIXME: Falta descripción para UPDATE_HOURS_OF_OPERATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '209', 'es-ES', 'FIXME: Falta descripción para CREATE_COPY_STATUS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '278', 'es-ES', 'FIXME: Falta descripción para UPDATE_VR_FORMAT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '254', 'es-ES', 'FIXME: Falta descripción para UPDATE_AUDIENCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '310', 'es-ES', 'FIXME: Falta descripción para VIEW_AUTHORITY_RECORD_NOTES');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '325', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.org.bounced_emails');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '270', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_ADDRESS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '340', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.global.juvenile_age_threshold');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '336', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.reshelving_complete.interval');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '220', 'es-ES', 'FIXME: Falta descripción para CREATE_ORG_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '299', 'es-ES', 'FIXME: Falta descripción para DELETE_TRANSLATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '246', 'es-ES', 'FIXME: Falta descripción para DELETE_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '224', 'es-ES', 'FIXME: Falta descripción para CREATE_RELEVANCE_ADJUSTMENT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '229', 'es-ES', 'FIXME: Falta descripción para DELETE_BIB_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '326', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.hold_expire_alert_interval');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '218', 'es-ES', 'FIXME: Falta descripción para CREATE_NET_ACCESS_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '305', 'es-ES', 'FIXME: Falta descripción para UPDATE_BIB_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '288', 'es-ES', 'FIXME: Falta descripción para CREATE_LOCALE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '286', 'es-ES', 'FIXME: Falta descripción para CREATE_BIB_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '264', 'es-ES', 'FIXME: Falta descripción para UPDATE_LANGUAGE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '330', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.hold_stalling.soft');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '291', 'es-ES', 'FIXME: Falta descripción para DELETE_ACQ_FUNDING_SOURCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '335', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.item_checkout_history.max');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '341', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.cat.bib.keep_on_empty');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '238', 'es-ES', 'FIXME: Falta descripción para DELETE_LASSO_MAP');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '243', 'es-ES', 'FIXME: Falta descripción para DELETE_ORG_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '334', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.global.password_regex');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '313', 'es-ES', 'FIXME: Falta descripción para CREATE_IMPORT_TRASH_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '321', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.lost_materials_processing_fee');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '312', 'es-ES', 'FIXME: Falta descripción para CREATE_IMPORT_ITEM_ATTR_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '258', 'es-ES', 'FIXME: Falta descripción para UPDATE_COPY_NOTE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '281', 'es-ES', 'FIXME: Falta descripción para UPDATE_PICKUP_LIB_FROM_HOLDS_SHELF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '284', 'es-ES', 'FIXME: Falta descripción para CREATE_AUTHORITY_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '273', 'es-ES', 'FIXME: Falta descripción para UPDATE_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '240', 'es-ES', 'FIXME: Falta descripción para DELETE_METABIB_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '260', 'es-ES', 'FIXME: Falta descripción para UPDATE_GROUP_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '295', 'es-ES', 'FIXME: Falta descripción para DELETE_BIB_IMPORT_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '283', 'es-ES', 'FIXME: Falta descripción para CREATE_AUTHORITY_IMPORT_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '232', 'es-ES', 'FIXME: Falta descripción para DELETE_COPY_STATUS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '302', 'es-ES', 'FIXME: Falta descripción para UPDATE_AUTHORITY_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '323', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.auth.opac_timeout');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '205', 'es-ES', 'FIXME: Falta descripción para CREATE_AUDIENCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '211', 'es-ES', 'FIXME: Falta descripción para CREATE_ITEM_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '204', 'es-ES', 'FIXME: Falta descripción para ASSIGN_GROUP_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '219', 'es-ES', 'FIXME: Falta descripción para CREATE_ORG_ADDRESS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '249', 'es-ES', 'FIXME: Falta descripción para DELETE_TRANSIT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '252', 'es-ES', 'FIXME: Falta descripción para REMOVE_GROUP_PERM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '228', 'es-ES', 'FIXME: Falta descripción para DELETE_AUDIENCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '217', 'es-ES', 'FIXME: Falta descripción para CREATE_METABIB_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '268', 'es-ES', 'FIXME: Falta descripción para UPDATE_METABIB_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '230', 'es-ES', 'FIXME: Falta descripción para DELETE_CIRC_DURATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '331', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.hold_boundary.hard');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '272', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_CLOSING');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '297', 'es-ES', 'FIXME: Falta descripción para DELETE_LOCALE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '206', 'es-ES', 'FIXME: Falta descripción para CREATE_BIB_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '296', 'es-ES', 'FIXME: Falta descripción para DELETE_BIB_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '327', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.hold_expire_interval');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '263', 'es-ES', 'FIXME: Falta descripción para UPDATE_ITEM_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '247', 'es-ES', 'FIXME: Falta descripción para DELETE_RELEVANCE_ADJUSTMENT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '337', 'es-ES', 'FIXME: Falta descripción paraUPDATE_ORG_UNIT_SETTING.circ.selfcheck.patron_login_timeout');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '241', 'es-ES', 'FIXME: Falta descripción para DELETE_NET_ACCESS_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '290', 'es-ES', 'FIXME: Falta descripción para CREATE_TRANSLATION');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '287', 'es-ES', 'FIXME: Falta descripción para CREATE_BIB_IMPORT_QUEUE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '239', 'es-ES', 'FIXME: Falta descripción para DELETE_LIT_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '314', 'es-ES', 'FIXME: Falta descripción para DELETE_IMPORT_ITEM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '234', 'es-ES', 'FIXME: Falta descripción para DELETE_ITEM_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '304', 'es-ES', 'FIXME: Falta descripción para UPDATE_BIB_IMPORT_IMPORT_FIELD_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '244', 'es-ES', 'FIXME: Falta descripción para DELETE_ORG_UNIT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '319', 'es-ES', 'FIXME: Falta descripción para UPDATE_IMPORT_TRASH_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '280', 'es-ES', 'FIXME: Falta descripción para MERGE_BIB_RECORDS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '339', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.selfcheck.require_patron_password');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '235', 'es-ES', 'FIXME: Falta descripción para DELETE_ITEM_TYPE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '307', 'es-ES', 'FIXME: Falta descripción para UPDATE_MARC_CODE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '316', 'es-ES', 'FIXME: Falta descripción para DELETE_IMPORT_TRASH_FIELD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '215', 'es-ES', 'FIXME: Falta descripción para CREATE_LASSO_MAP');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '276', 'es-ES', 'FIXME: Falta descripción para UPDATE_TRANSIT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '338', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.circ.selfcheck.alert_on_checkout_event');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '221', 'es-ES', 'FIXME: Falta descripción para CREATE_ORG_UNIT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '269', 'es-ES', 'FIXME: Falta descripción para UPDATE_NET_ACCESS_LEVEL');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '328', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.credit.payments.allow');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '318', 'es-ES', 'FIXME: Falta descripción para UPDATE_IMPORT_ITEM_ATTR_DEF');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '208', 'es-ES', 'FIXME: Falta descripción para CREATE_CIRC_MOD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '282', 'es-ES', 'FIXME: Falta descripción para CREATE_ACQ_FUNDING_SOURCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '259', 'es-ES', 'FIXME: Falta descripción para UPDATE_COPY_STATUS');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '333', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.opac.barcode_regex');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '285', 'es-ES', 'FIXME: Falta descripción para CREATE_AUTHORITY_RECORD_NOTE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '309', 'es-ES', 'FIXME: Falta descripción para VIEW_ACQ_FUNDING_SOURCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '317', 'es-ES', 'FIXME: Falta descripción para UPDATE_IMPORT_ITEM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '343', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.patron.password.use_phone');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '250', 'es-ES', 'FIXME: Falta descripción para DELETE_VR_FORMAT');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '303', 'es-ES', 'FIXME: Falta descripción para UPDATE_AUTHORITY_RECORD_NOTE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '248', 'es-ES', 'FIXME: Falta descripción para DELETE_SURVEY');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '216', 'es-ES', 'FIXME: Falta descripción para CREATE_LIT_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '231', 'es-ES', 'FIXME: Falta descripción para DELETE_CIRC_MOD');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '298', 'es-ES', 'FIXME: Falta descripción para DELETE_MARC_CODE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '267', 'es-ES', 'FIXME: Falta descripción para UPDATE_LIT_FORM');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '300', 'es-ES', 'FIXME: Falta descripción para UPDATE_ACQ_FUNDING_SOURCE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '236', 'es-ES', 'FIXME: Falta descripción para DELETE_LANGUAGE');
INSERT INTO config.i18n_core (fq_field, identity_value, translation, string) VALUES ('ppl.description', '322', 'es-ES', 'FIXME: Falta descripción para UPDATE_ORG_UNIT_SETTING.cat.default_item_price');
