{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "All Available Sources", 
    "TEMPLATE_CONF_SELECT_CANCEL": "Select the value, or cancel:", 
    "OPERATORS_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NULL_BLANK": "Is NULL or Blank", 
    "OPERATORS_LIKE": "Contains Matching substring", 
    "WIDGET_MONTHS": "Month(s)", 
    "LINK_NULLABLE_RIGHT": "Parent", 
    "TFORMS_LABEL_AVERAGE": "Average", 
    "TEMPLATE_CONF_CONFIRM_STATE": "Click OK for TRUE and Cancel for FALSE.", 
    "OPERATORS_EQUALS": "Equals", 
    "FILTERS_LABEL_BETWEEN": "Between", 
    "OPERATORS_IN_LIST": "In list", 
    "TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):", 
    "OPERATORS_NOT_IN_LIST": "Not in list", 
    "FILTERS_LABEL_NOT_IN": "Not in list", 
    "SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate", 
    "FILTERS_LABEL_GT_TIME": "After (Date/Time)", 
    "OPERATORS_IS_NULL": "Is NULL", 
    "TEMPLATE_CONF_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?", 
    "OPERATORS_IS_NOT_NULL": "Is not NULL", 
    "TEMPLATE_CONF_CONFIRM_RESET": "You have already added the [${0}] field\nfrom the [${1}] source. Click OK if you\nwould like to reset this field.", 
    "OPERATORS_GT_EQUAL": "Greater than or equal to", 
    "TRANSFORMS_MONTH_TRUNC": "Year + Month", 
    "FILTERS_LABEL_NULL": "Is NULL", 
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Please provide a report folder", 
    "OPERATORS_GT_TIME": "After (Date/Time)", 
    "TRANSFORMS_YEAR_TRUNC": "Year", 
    "TRANSFORMS_UPPER": "Upper case", 
    "FOLDERS_REPORTS": "Reports", 
    "LINK_NULLABLE_LEFT": "Child", 
    "TRANSFORMS_COUNT_DISTINCT": "Count Distinct", 
    "FOLDER_WINDOW_COLNAME_SELECT": "Select", 
    "TRANSFORMS_FIRST": "First Value", 
    "TFORMS_LABEL_LOWER": "Lower case", 
    "TFORMS_LABEL_COUNT": "Count", 
    "TRANSFORMS_HOD": "Hour of day", 
    "WIDGET_RELATIVE_DATE": "Relative Date", 
    "FILTERS_LABEL_LESS_THAN": "Less than", 
    "TEMPLATE_CONF_SUCCESS_SAVE": "Template ${0} was successfully saved.", 
    "TFORMS_LABEL_MOY": "Month of Year", 
    "REPORT_EDITOR_OUTPUT_FOLDERS": "Output Folders", 
    "TRANSFORMS_MAX": "Max", 
    "TRANSFORMS_MIN": "Min", 
    "TRANSFORMS_SUM": "Sum", 
    "TRANSFORMS_FIRST_WORD": "First contiguous non-space string", 
    "TRANSFORMS_MONTHS_AGO": "Months ago", 
    "SOURCE_BROWSE_AGGREGATE": "Aggregate", 
    "TFORMS_LABEL_DATE": "Date", 
    "WIDGET_YEARS": "Year(s)", 
    "FILTERS_LABEL_LT_TIME": "Before (Date/Time)", 
    "TRANSFORMS_COUNT": "Count", 
    "WIDGET_REAL_DATE": "Real Date", 
    "OPERATORS_LT_TIME": "Before (Date/Time)", 
    "TFORMS_LABEL_MAX": "Max", 
    "TEMPLATE_CONF_FALSE": "False", 
    "TEMPLATE_CONF_BARE": "Bare", 
    "TRANSFORMS_LAST": "Last Value", 
    "TFORMS_LABEL_MIN": "Min", 
    "REPORT_EDITOR_REPORT_FOLDERS": "Report Folders", 
    "TRANSFORMS_QOY": "Quarter of Year", 
    "OPERATORS_NOT_NULL_BLANK": "Is not NULL or Blank", 
    "FILTERS_LABEL_NOT_BETWEEN": "Not between", 
    "TEMPLATE_CONF_EQUALS": "Equals", 
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Please provide an output folder", 
    "FILTERS_LABEL_GREATER_THAN": "Greater than", 
    "FOLDERS_OUTPUT": "Output", 
    "TRANSFORMS_AVERAGE": "Average", 
    "FOLDERS_TEMPLATES": "Templates", 
    "TFORMS_LABEL_DAY_NAME": "Day Name", 
    "WIDGET_DAYS": "Day(s)", 
    "TRANSFORMS_ROUND": "Round", 
    "FOLDERS_TEMPLATE": "Template", 
    "TRANSFORMS_HOUR_TRUNC": "Hour", 
    "TFORMS_LABEL_HOUR_TRUNC": "Hour", 
    "TRANSFORMS_MOY": "Month of Year", 
    "LINK_NULLABLE_NONE": "None", 
    "RPT_BUILDER_CONFIRM_SAVE": "Name : ${0}\nDescription: ${1}\nSave Template?", 
    "TFORMS_LABEL_DOY": "Day of Year", 
    "TRANSFORMS_DATE": "Date", 
    "FOLDERS_REPORT": "Report", 
    "TFORMS_LABEL_DOW": "Day of Week", 
    "FILTERS_LABEL_LT_EQUAL": "Less than or equal to", 
    "TFORMS_LABEL_INT": "Drop trailing decimals", 
    "OPERATORS_GTE_TIME": "On or After (Date/Time)", 
    "TFORMS_LABEL_DOM": "Day of Month", 
    "FOLDER_WINDOW_COLNAME_NONE": "None", 
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Please enter a report name", 
    "OPERATORS_LT_EQUAL": "Less than or equal to", 
    "TFORMS_LABEL_MONTHS_AGO": "Months ago", 
    "TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string", 
    "FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}", 
    "FILTERS_LABEL_GTE_TIME": "On or After (Date/Time)", 
    "TFORMS_LABEL_FIRST": "First Value", 
    "TRANSFORMS_AGE": "Age", 
    "FILTERS_LABEL_LIKE": "Contains Matching substring", 
    "TEMPLATE_CONF_TRUE": "True", 
    "SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?", 
    "TRANSFORMS_QUARTERS_AGO": "Quarters ago", 
    "TFORMS_LABEL_MONTH_TRUNC": "Year + Month", 
    "TEMPLATE_CONF_IN": "Field matches one of list (comma separated):", 
    "FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NOT_NULL": "Is not NULL", 
    "TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):", 
    "TFORMS_LABEL_UPPER": "Upper case", 
    "TRANSFORMS_SUBSTRING": "Substring", 
    "FILTERS_LABEL_GT_EQUAL": "Greater than or equal to", 
    "TEMPLATE_CONF_RAW_DATA": "Raw Data", 
    "TFORMS_LABEL_HOD": "Hour of day", 
    "FILTERS_LABEL_NOT_NULL_BLANK": "Is not NULL or Blank", 
    "TFORMS_LABEL_SUM": "Sum", 
    "LINK_NULLABLE_DEFAULT": "Default", 
    "FILTERS_LABEL_IN": "In list", 
    "REPORT_EDITOR_INVALID_DATE_ALERT": "invalid start date -  YYYY-MM-DD", 
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Change Folders", 
    "TRANSFORMS_LOWER": "Lower case", 
    "TRANSFORMS_MONTH_NAME": "Month Name", 
    "TRANSFORMS_DOW": "Day of Week", 
    "TEMPLATE_CONF_PROMPT_CHANGE": "Change the column header to: ${0}", 
    "OPERATORS_NOT_BETWEEN": "Not between", 
    "TRANSFORMS_DOY": "Day of Year", 
    "TFORMS_LABEL_AGE": "Age", 
    "TRANSFORMS_BARE": "Raw Data", 
    "TRANSFORMS_DOM": "Day of Month", 
    "TFORMS_LABEL_MONTH_NAME": "Month Name", 
    "TFORMS_LABEL_ROUND": "Round", 
    "OPERATORS_GREATER_THAN": "Greater than", 
    "SOURCE_SETUP_CORE_SOURCES": "Core Sources", 
    "TFORMS_LABEL_LAST": "Last Value", 
    "FILTERS_LABEL_EQUALS": "Equals", 
    "FOLDER_WINDOW_COLNAME_ALL": "All", 
    "TFORMS_LABEL_RAW_DATA": "Raw Data", 
    "TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct", 
    "TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)", 
    "TEMPLATE_CONF_NOT_BETWEEN": "Field value is not between (comma separated):", 
    "TRANSFORMS_INT": "Drop trailing decimals", 
    "FILTERS_LABEL_LSE_TIME": "On or Before (Date/Time)", 
    "TRANSFORMS_DAY_NAME": "Day Name", 
    "FOLDER_WINDOW_SELECT_ITEM": "Please select an item from the list", 
    "TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)", 
    "OPERATORS_LTE_TIME": "On or Before (Date/Time)", 
    "TEMPLATE_CONF_DEFAULT": "Value ${0}:", 
    "TFORMS_LABEL_YEAR_TRUNC": "Year", 
    "TRANSFORMS_WOY": "Week of Year", 
    "TFORMS_LABEL_WOY": "Week of Year", 
    "TFORMS_LABEL_QUARTERS_AGO": "Quarters ago", 
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Boolean Value", 
    "OPERATORS_NULL_BLANK": "Is NULL or Blank", 
    "TEMPLATE_CONF_BETWEEN": "Field value is between (comma separated):", 
    "TFORMS_LABEL_QOY": "Quarter of Year", 
    "WIDGET_QUARTERS": "Quarter(s)", 
    "OPERATORS_LESS_THAN": "Less than", 
    "OPERATORS_BETWEEN": "Between"
}