{
    "AUTO_ATTR_VALUE_button_cancel_existing": "Cancel selected", 
    "AUTO_ATTR_VALUE_reserve_brsrc": "Reserve Selected", 
    "AUTO_ATTR_VALUE_next": "Next", 
    "HERE_ARE_EXISTING_BRESV": "Existing reservations for", 
    "ON_FLY_ERROR": "Error attempting to make item a bookable resource:", 
    "AUTO_ATTR_VALUE_button_edit_existing": "Edit selected", 
    "AUTO_ending_at": "and", 
    "AUTO_arbitrary_resource": "Enter the barcode of a cataloged, bookable resource:", 
    "NO_BRT_RESULTS": "There are no bookable resource types registered.", 
    "AUTO_ATTR_VALUE_reserve_brt": "Reserve Any", 
    "AUTO_brt_noncat_only": "Show only non-cataloged bookable resource types", 
    "OUTSTANDING_BRESV": "Outstanding reservations for patron", 
    "INVALID_TS_RANGE": "You must choose a valid start and end time for the reservation.", 
    "AUTO_or": "- Or -", 
    "CREATE_BRESV_OK_MISSING_TARGET_WILL_CANCEL": "Since the requested resource could not be targeted, this\nreservation will now be canceled.", 
    "ERROR_FETCHING_AOUS": "Could not retrieve organizational unit settings.\nThis is a non-fatal error, but you may wish to\ncontact your system administrator.", 
    "NEED_EXACTLY_ONE_BRT_PASSED_IN": "Can't book multiple resource types at once", 
    "CXL_BRESV_SUCCESS": "Canceled ${0} reservation(s)", 
    "UNTARGETED": "None targeted", 
    "CREATE_BRESV_SERVER_ERROR": "Server error trying to create reservation: ", 
    "ON_FLY_NO_RESPONSE": "No response from server attempting to make item a bookable resource.", 
    "AUTO_patron_barcode": "Reserve to patron barcode:", 
    "NO_EXISTING_BRESV": "This user has no existing reservations at this time.", 
    "GET_BRESV_LIST_ERR": "Error while retrieving reservation list: ", 
    "AUTO_explain_bookable": "To reserve an item that is not yet registered as a bookable resource, find it in the catalog or under <em>Display Item</em>, and select <em>Make Item Bookable</em> or <em>Book Item Now</em> there.", 
    "NO_TARG_DIV": "Could not find target div", 
    "CREATE_BRESV_SERVER_NO_RESPONSE": "No response from server after trying to create reservation.", 
    "AUTO_bresv_grid_type": "Type", 
    "AUTO_choose_a_brt": "Choose a Bookable Resource Type", 
    "NO_BRA_RESULTS": "Couldn't retrieve booking resource attributes.", 
    "AUTO_i_need_this_resource": "I need this resource...", 
    "AUTO_bresv_grid_end_time": "End time", 
    "BRSRC_NOT_FOUND": "Could not locate that resource.", 
    "AUTO_starting_at": "Between", 
    "CXL_BRESV_FAILURE2": "Error canceling reservations:\n", 
    "CREATE_BRESV_OK_MISSING_TARGET": "Created ${0} reservation(s), but ${1} of these could not target any resources.\n\nThis means that it won't be possible to fulfill some of these\nreservations until a suitable resource becomes available.", 
    "CREATE_BRESV_OK": "Created ${0} reservation(s)", 
    "CREATE_BRESV_LOCAL_ERROR": "Exception trying to create reservation: ", 
    "GET_BRESV_LIST_NO_RESULT": "No results from server retrieving reservation list.", 
    "BRSRC_RETRIVE_ERROR": "Error retrieving resource: ", 
    "AUTO_bresv_grid_resource": "Resource", 
    "WHERES_THE_BARCODE": "Enter a patron's barcode to make a reservation.", 
    "AUTO_pickup_lib_selector": "Choose the pickup library for this reservation:", 
    "NO_USABLE_BRSRC": "No reservable resources.  Adjust start and end time\nuntil a resource is available for reservation.", 
    "CREATE_BRESV_OK_MISSING_TARGET_BLOCKED_BY_CIRC": "The desired reservation(s) are blocked by circulation(s) with the following due date(s):\n${0}", 
    "CXL_BRESV_SELECT_SOMETHING": "You have not selected any reservations to cancel.", 
    "COULD_NOT_RETRIEVE_BRT_PASSED_IN": "Error retrieving booking resource type", 
    "CXL_BRESV_FAILURE": "Error canceling reservations; server silent.", 
    "ACTOR_CARD_NOT_FOUND": "Patron barcode not found. Please try again.", 
    "SELECT_A_BRSRC_THEN": "You have clicked 'Reserve Selected', but nothing is selected!\n\nYou must select a resource from the large box above.\n\n***  If resources that you would select are highlighted in RED, ***\nthese items are not available during the requested time; if\npossible, choose another resource or change the reservation time.", 
    "GET_PATRON_NO_RESULT": "No server response after attempting to look up patron by barcode.", 
    "AUTO_with_these_attr": "With these attributes:", 
    "ANY": "ANY", 
    "AUTO_bresv_grid_start_time": "Start time"
}