{
    "SOURCE_SETUP_ALL_AVAIL_SOURCES": "V\u0161echny dostupn\u00e9 zdroje", 
    "TEMPLATE_CONF_SELECT_CANCEL": "Vyberte hodnotu, nebo zru\u0161t\u011b:", 
    "OPERATORS_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NULL_BLANK": "Je nulov\u00fd nebo pr\u00e1zdn\u00fd", 
    "OPERATORS_LIKE": "Contains Matching substring", 
    "WIDGET_MONTHS": "M\u011bs\u00edc(e)", 
    "LINK_NULLABLE_RIGHT": "Parent", 
    "TFORMS_LABEL_AVERAGE": "Pr\u016fm\u011br", 
    "TEMPLATE_CONF_CONFIRM_STATE": "Klikn\u011bte na OK pro PRAVDU a ZRU\u0160IT pro NEPRAVDU.", 
    "OPERATORS_EQUALS": "Je roven", 
    "FILTERS_LABEL_BETWEEN": "Mezi", 
    "OPERATORS_IN_LIST": "V seznamu", 
    "TEMPLATE_CONF_NOT_IN": "Field does not match one of list (comma separated):", 
    "OPERATORS_NOT_IN_LIST": "Nen\u00ed v seznamu", 
    "FILTERS_LABEL_NOT_IN": "Nen\u00ed v seznamu", 
    "SOURCE_BROWSE_NON_AGGREGATE": "Non-Aggregate", 
    "FILTERS_LABEL_GT_TIME": "Po (Datum/\u010cas)", 
    "OPERATORS_IS_NULL": "Je nulov\u00fd", 
    "TEMPLATE_CONF_CONFIRM_SAVE": "Jm\u00e9no : ${0}\nPopis : ${1}\nUlo\u017eit \u0161ablonu?", 
    "OPERATORS_IS_NOT_NULL": "Nen\u00ed nulov\u00fd", 
    "TEMPLATE_CONF_CONFIRM_RESET": "Je\u0161t\u011b jste nep\u0159idal/a pole [${0}]\nze zdroje [${1}].  Klikn\u011bte na OK, pokud\nchcete toto pole zru\u0161it.", 
    "OPERATORS_GT_EQUAL": "V\u011bt\u0161\u00ed nebo rovno", 
    "TRANSFORMS_MONTH_TRUNC": "Rok + M\u011bs\u00edc", 
    "FILTERS_LABEL_NULL": "Je nulov\u00fd", 
    "REPORT_EDITOR_PROVIDE_FOLDER_ALERT": "Vyberte pros\u00edm slo\u017eku pro zpr\u00e1vy", 
    "OPERATORS_GT_TIME": "Po (Datum/\u010cas)", 
    "TRANSFORMS_YEAR_TRUNC": "Rok", 
    "TRANSFORMS_UPPER": "Velk\u00e1 p\u00edsmena", 
    "FOLDERS_REPORTS": "Zpr\u00e1vy", 
    "LINK_NULLABLE_LEFT": "Child", 
    "TRANSFORMS_COUNT_DISTINCT": "Count Distinct", 
    "FOLDER_WINDOW_COLNAME_SELECT": "Vybrat", 
    "TRANSFORMS_FIRST": "Prvn\u00ed hodnota", 
    "TFORMS_LABEL_LOWER": "Mal\u00e1 p\u00edsmena", 
    "TFORMS_LABEL_COUNT": "Po\u010det", 
    "TRANSFORMS_HOD": "Hodina", 
    "WIDGET_RELATIVE_DATE": "Relative Date", 
    "FILTERS_LABEL_LESS_THAN": "Men\u0161\u00ed ne\u017e", 
    "TEMPLATE_CONF_SUCCESS_SAVE": "\u0160ablona ${0} byla \u00fasp\u011b\u0161n\u011b ulo\u017eena.", 
    "TFORMS_LABEL_MOY": "M\u011bs\u00edc", 
    "REPORT_EDITOR_OUTPUT_FOLDERS": "V\u00fdstupn\u00ed polo\u017eky", 
    "TRANSFORMS_MAX": "Max", 
    "TRANSFORMS_MIN": "Min", 
    "TRANSFORMS_SUM": "Sum", 
    "TRANSFORMS_FIRST_WORD": "First contiguous non-space string", 
    "TRANSFORMS_MONTHS_AGO": "P\u0159ed m\u011bs\u00edci", 
    "SOURCE_BROWSE_AGGREGATE": "Aggregate", 
    "TFORMS_LABEL_DATE": "Datum", 
    "WIDGET_YEARS": "Rok(y)", 
    "FILTERS_LABEL_LT_TIME": "P\u0159ed (Datum/\u010cas)", 
    "TRANSFORMS_COUNT": "Po\u010det", 
    "WIDGET_REAL_DATE": "Re\u00e1ln\u00e9 datum", 
    "OPERATORS_LT_TIME": "P\u0159ed (Datum/\u010cas)", 
    "TFORMS_LABEL_MAX": "Max", 
    "TEMPLATE_CONF_FALSE": "Nepravda", 
    "TEMPLATE_CONF_BARE": "Bare", 
    "TRANSFORMS_LAST": "Posledn\u00ed hodnota", 
    "TFORMS_LABEL_MIN": "Min", 
    "REPORT_EDITOR_REPORT_FOLDERS": "Slo\u017eka zpr\u00e1v", 
    "TRANSFORMS_QOY": "\u010ctvrtlet\u00ed", 
    "OPERATORS_NOT_NULL_BLANK": "Je nenulov\u00fd nebo pr\u00e1zdn\u00fd", 
    "FILTERS_LABEL_NOT_BETWEEN": "Nen\u00ed mezi", 
    "TEMPLATE_CONF_EQUALS": "Je roven", 
    "REPORT_EDITOR_PROVIDE_OUTPUT_ALERT": "Vyberte pros\u00edm slo\u017eku pro v\u00fdstupy", 
    "FILTERS_LABEL_GREATER_THAN": "V\u011bt\u0161\u00ed ne\u017e", 
    "FOLDERS_OUTPUT": "V\u00fdstup", 
    "TRANSFORMS_AVERAGE": "Pr\u016fm\u011br", 
    "FOLDERS_TEMPLATES": "\u0160ablony", 
    "TFORMS_LABEL_DAY_NAME": "N\u00e1zev dne", 
    "WIDGET_DAYS": "Den/Dny", 
    "TRANSFORMS_ROUND": "Okolo", 
    "FOLDERS_TEMPLATE": "\u0160ablona", 
    "TRANSFORMS_HOUR_TRUNC": "Hodina", 
    "TFORMS_LABEL_HOUR_TRUNC": "Hodina", 
    "TRANSFORMS_MOY": "M\u011bs\u00edc", 
    "LINK_NULLABLE_NONE": "\u017d\u00e1dn\u00fd", 
    "RPT_BUILDER_CONFIRM_SAVE": "Jm\u00e9no : ${0}\nPopis : ${1}\nUlo\u017eit \u0161ablonu?", 
    "TFORMS_LABEL_DOY": "Den roku", 
    "TRANSFORMS_DATE": "Datum", 
    "FOLDERS_REPORT": "Zpr\u00e1va", 
    "TFORMS_LABEL_DOW": "Den t\u00fddne", 
    "FILTERS_LABEL_LT_EQUAL": "Men\u0161\u00ed nebo rovno", 
    "TFORMS_LABEL_INT": "Drop trailing decimals", 
    "OPERATORS_GTE_TIME": "V nebo po datu (Datum/\u010cas)", 
    "TFORMS_LABEL_DOM": "Den m\u011bs\u00edce", 
    "FOLDER_WINDOW_COLNAME_NONE": "\u017d\u00e1dn\u00fd", 
    "REPORT_EDITOR_ENTER_NAME_ALERT": "Zadejte pros\u00edm jm\u00e9no zpr\u00e1vy", 
    "OPERATORS_LT_EQUAL": "Men\u0161\u00ed nebo rovno", 
    "TFORMS_LABEL_MONTHS_AGO": "P\u0159ed m\u011bs\u00edci", 
    "TFORMS_LABEL_FIRST_WORD": "First contiguous non-space string", 
    "FOLDER_WINDOW_REPORT_OUTPUT": "Report Output: ${0}", 
    "FILTERS_LABEL_GTE_TIME": "V nebo po datu (Datum/\u010cas)", 
    "TFORMS_LABEL_FIRST": "Prvn\u00ed hodnota", 
    "TRANSFORMS_AGE": "St\u00e1\u0159\u00ed", 
    "FILTERS_LABEL_LIKE": "Contains Matching substring", 
    "TEMPLATE_CONF_TRUE": "Pravda", 
    "SOURCE_SETUP_CONFIRM_EXIT": "You have started building a template!\n Selecting a new starting source will destroy the current template and start over.  Is this OK?", 
    "TRANSFORMS_QUARTERS_AGO": "P\u0159ed \u010dtvrtlet\u00edmi", 
    "TFORMS_LABEL_MONTH_TRUNC": "Rok + M\u011bs\u00edc", 
    "TEMPLATE_CONF_IN": "Field matches one of list (comma separated):", 
    "FILTERS_LABEL_ILIKE": "Contains Matching substring (ignore case)", 
    "FILTERS_LABEL_NOT_NULL": "Nen\u00ed nulov\u00fd", 
    "TEMPLATE_CONF_NO_MATCH": "Field does not match one of list (comma separated):", 
    "TFORMS_LABEL_UPPER": "Velk\u00e1 p\u00edsmena", 
    "TRANSFORMS_SUBSTRING": "Substring", 
    "FILTERS_LABEL_GT_EQUAL": "V\u011bt\u0161\u00ed nebo rovno", 
    "TEMPLATE_CONF_RAW_DATA": "Nezpracovan\u00e9 \u00fadaje", 
    "TFORMS_LABEL_HOD": "Hodina", 
    "FILTERS_LABEL_NOT_NULL_BLANK": "Je nenulov\u00fd nebo pr\u00e1zdn\u00fd", 
    "TFORMS_LABEL_SUM": "Sum", 
    "LINK_NULLABLE_DEFAULT": "Default", 
    "FILTERS_LABEL_IN": "V seznamu", 
    "REPORT_EDITOR_INVALID_DATE_ALERT": "neplatn\u00e9 datum zah\u00e1jen\u00ed - RRRR-MM-DD", 
    "FOLDER_WINDOW_CHANGE_FOLDERS": "Zm\u011bnit slo\u017eky", 
    "TRANSFORMS_LOWER": "Mal\u00e1 p\u00edsmena", 
    "TRANSFORMS_MONTH_NAME": "N\u00e1zev m\u011bs\u00edce", 
    "TRANSFORMS_DOW": "Den t\u00fddne", 
    "TEMPLATE_CONF_PROMPT_CHANGE": "Zm\u011bnit z\u00e1hlav\u00ed sloupce na: ${0}", 
    "OPERATORS_NOT_BETWEEN": "Nen\u00ed mezi", 
    "TRANSFORMS_DOY": "Den roku", 
    "TFORMS_LABEL_AGE": "St\u00e1\u0159\u00ed", 
    "TRANSFORMS_BARE": "Nezpracovan\u00e9 \u00fadaje", 
    "TRANSFORMS_DOM": "Den m\u011bs\u00edce", 
    "TFORMS_LABEL_MONTH_NAME": "N\u00e1zev m\u011bs\u00edce", 
    "TFORMS_LABEL_ROUND": "Okolo", 
    "OPERATORS_GREATER_THAN": "V\u011bt\u0161\u00ed ne\u017e", 
    "SOURCE_SETUP_CORE_SOURCES": "Z\u00e1kladn\u00ed zdroje", 
    "TFORMS_LABEL_LAST": "Posledn\u00ed hodnota", 
    "FILTERS_LABEL_EQUALS": "Je roven", 
    "FOLDER_WINDOW_COLNAME_ALL": "V\u0161e", 
    "TFORMS_LABEL_RAW_DATA": "Nezpracovan\u00e9 \u00fadaje", 
    "TFORMS_LABEL_COUNT_DISTINCT": "Count Distinct", 
    "TFORMS_LABEL_FIRST5": "First 5 characters (for US ZIP code)", 
    "TEMPLATE_CONF_NOT_BETWEEN": "Hodnota pole nen\u00ed mezi (odd\u011bleno \u010d\u00e1rkou):", 
    "TRANSFORMS_INT": "Drop trailing decimals", 
    "FILTERS_LABEL_LSE_TIME": "V nebo p\u0159ed (Datum/\u010cas)", 
    "TRANSFORMS_DAY_NAME": "N\u00e1zev dne", 
    "FOLDER_WINDOW_SELECT_ITEM": "Vyberte pros\u00edm polo\u017eku ze seznamu", 
    "TRANSFORMS_FIRST5": "First 5 characters (for US ZIP code)", 
    "OPERATORS_LTE_TIME": "V nebo p\u0159ed (Datum/\u010cas)", 
    "TEMPLATE_CONF_DEFAULT": "Hodnota ${0}:", 
    "TFORMS_LABEL_YEAR_TRUNC": "Rok", 
    "TRANSFORMS_WOY": "T\u00fdden roku", 
    "TFORMS_LABEL_WOY": "T\u00fdden roku", 
    "TFORMS_LABEL_QUARTERS_AGO": "P\u0159ed \u010dtvrtlet\u00edmi", 
    "TEMPLATE_CONF_BOOLEAN_VALUE": "Booleovsk\u00e1 hodnota", 
    "OPERATORS_NULL_BLANK": "Je nulov\u00fd nebo pr\u00e1zdn\u00fd", 
    "TEMPLATE_CONF_BETWEEN": "Hodnota pole je mezi (odd\u011bleno \u010d\u00e1rkou):", 
    "TFORMS_LABEL_QOY": "\u010ctvrtlet\u00ed", 
    "WIDGET_QUARTERS": "\u010ctvrtlet\u00ed", 
    "OPERATORS_LESS_THAN": "Men\u0161\u00ed ne\u017e", 
    "OPERATORS_BETWEEN": "Mezi"
}