{
    "NO_PAYLOAD": "We did not receive further information from the server about this attempt to capture.", 
    "TITLE": "Title", 
    "PRINT": "<u>P</u>rint", 
    "AUTO_resource_barcode": "Enter barcode:", 
    "DURATION": "Reserved from", 
    "NEEDS_ROUTED_TO": "This item need to be routed to", 
    "PRINTED_BY": "Printed by", 
    "CAPTURE_TRANSIT_SOURCE": "From:", 
    "CAPTURE_INFO": "Capture Information", 
    "AUTO_ATTR_VALUE_capture": "Capture", 
    "AUTHOR": "Author", 
    "CAPTURE_BRESV_BRSRC": "Resource barcode:", 
    "SLIP_DATE": "Slip date", 
    "RESERVATION_SHELF": "RESERVATION SHELF", 
    "UNKNOWN_PROBLEM": "An unknown problem occurred during capture attempt.", 
    "FAILURE": "Capture failed", 
    "CAPTURE_CAUSES_TRANSIT": "This item is now in transit!", 
    "RESERVED": "Reserved for patron", 
    "SUCCESS": "Capture succeeded", 
    "REQUEST": "Request time", 
    "AT": "at", 
    "CAPTURE_BRESV_PICKUP_LIB": "Pickup library:", 
    "CAPTURED_NOTHING": "Didn't capture anything.", 
    "TRANSIT": "*** TRANSIT ***", 
    "BARCODE": "Barcode", 
    "AUTO_pickup_lib_selector": "Pickup library:", 
    "CAPTURE_TRANSIT_DEST": "To:", 
    "PRINT_ACCESSKEY": "P", 
    "CAPTURE_BRESV_DATES": "Reservation time:", 
    "HERES_WHAT_WE_KNOW": "The following information is available about the failed capture:", 
    "AUTO_capture_heading": "Capture Reserved Resources"
}