#!/bin/bash
#
# Copyright (C) 2008 Equinox Software, Inc.
# Kevin Beswick <kevinbeswick00@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

# Shows configuration options of Evergreen

prefix=/openils
exec_prefix=/openils
datarootdir=${prefix}/share

function showInstalled {
	if test "" = ""; then
		echo "EG_CORE"
	fi
	if test "" = ""; then
		echo "EG_WEB"
	fi
	if test "" = ""; then
		echo "EG_REPORTER"
	fi
	if test "" = ""; then
		echo "EG_CLIENT"
	fi
	if test "#" = ""; then
		echo "EG_JAVA"
	fi
	if test "#" = ""; then
		echo "EG_PYTHON"
	fi


}

function showAll {
	 echo Open-ILS trunk	
	 echo PREFIX=/openils
	 echo BINDIR=${exec_prefix}/bin
	 echo LIBDIR=${exec_prefix}/lib
	 echo TMP=/tmp
	 echo INCLUDEDIR=${prefix}/include
	 echo SYSCONFDIR=/openils/conf
	 echo APXS2=/usr/bin/apxs2
	 echo APACHE2_HEADERS=/usr/include/apache2
	 echo APR_HEADERS=/usr/include/apr-1.0
	 echo LIBXML2_HEADERS=/usr/include/libxml2/
	 echo 
	 echo "Installed modules:"
	 showInstalled;
}


function showHelp {
	 echo 
	 echo "------------------------------------------------------------"
	 echo " eg_config                                                  "
	 echo " Shows configuration of evergreen                           "
	 echo "------------------------------------------------------------"
	 echo
	 echo "Usage: eg_config [--option]"
	 echo 
	 echo "Options: "
	 echo
	 echo "--help                  displays help"
	 echo "--version               displays version number of evergreen"
	 echo "--installed             displays options that were installed"
	 echo "--prefix                displays prefix"
	 echo "--bindir                displays bindir"
	 echo "--libdir                displays libdir"
	 echo "--tmp                   displays tmp"
	 echo "--includedir            displays includedir"
	 echo "--sysconfdir            displays sysconfdir"
	 echo "--apxs                  displays location of apxs"
	 echo "--apache                displays location of apache2 headers"
	 echo "--apr                   displays location of apr headers"
	 echo "--libxml                displays location of libxml2 headers" 
	 echo
}

case "$1" in
     --installed)
		showInstalled;
		;;
     --cconfig) cconfig;
      		;;
     --libxml)
		echo /usr/include/libxml2/;
		;;
     --apr)
		echo /usr/include/apr-1.0;
		;;
     --apache)
		echo /usr/include/apache2;
		;;
     --prefix)
		echo /openils
		;;
     --version) 
		echo Open-ILS trunk;
		;;
     --bindir)
		echo ${exec_prefix}/bin
		;;
     --libdir)
		echo ${exec_prefix}/lib;
		;;
     --sysconfdir)
		echo /openils/conf;
		;;
     --localstatedir)
		echo ${prefix}/var;
		;;
     --tmpdir)
		echo /tmp;
		;;
     --apxs)
		echo /usr/bin/apxs2;
		;;
     --includedir)
		echo ${prefix}/include;
		;;
     --docdir)
		echo ${datarootdir}/doc/${PACKAGE_TARNAME};
		;;
     --help)
		showHelp;
		;;
     *)
		showAll;
		;;
esac
