{
    "COPY_LOOKUP_NO_RESPONSE": "No response looking up copies by barcode", 
    "AUTO_th_call_number": "Call number", 
    "FOR": "for", 
    "AUTO_th_copy_location": "Copy location", 
    "AUTO_owning_lib_selector": "See pull list for library:", 
    "AUTO_interval_in_days": "Generate list for this many days hence: ", 
    "AUTO_th_title_or_name": "Title or name", 
    "AUTO_th_barcode": "Barcode", 
    "PULL_LIST_NO_RESPONSE": "No response from server trying to get pull list!", 
    "COPY_MISSING": "Unexpected error: No information for copy: ", 
    "AUTO_ATTR_VALUE_fetch": "Fetch", 
    "PULL_LIST_ERROR": "Error trying to fetch pull list: ", 
    "AT": "at", 
    "AUTO_ATTR_VALUE_print": "Print", 
    "AUTO_th_pickup_lib": "Pickup library", 
    "AUTO_th_resv_details": "Reservation details", 
    "COPY_LOOKUP_ERROR": "Error looking up copies by barcode: ", 
    "AUTO_no_results": "No results.", 
    "AUTO_pull_list_title": "Booking Pull List"
}